Made the publish script a bit safer.

diff --git a/bin/publish b/bin/publish
--- a/bin/publish
+++ b/bin/publish
@@ -1,22 +1,28 @@
 #!/usr/bin/env bash
 
+jekyll build
+
+if [ $? -ne 0 ]; then
+  echo "Jekyll build failed!"
+  exit 1
+fi
+
 mkdir /tmp/jekyll
 rm -rf /tmp/jekyll/*
-jekyll build -d /tmp/jekyll
-
-# publish on github only if jekyll build was successful
-if [ $? -eq 0 ]; then
-  echo "Jekyll build failed!"
-  exit
-end
-
+cp -R ./_site/* /tmp/jekyll
 git checkout master
-rm -rf ./*
-cp -Rv /tmp/jekyll/* ./
-git add -A .
-git commit -m "Publish site $(date)"
-#git push origin master
-#git checkout source
-rm -rf /tmp/jekyll
-echo "Published to Github."
 
+if [ $? -ne 0 ]; then
+  echo "Unable to checkout master! Do you have uncommited changes?"
+  exit 1
+fi
+
+rm -rf ./*
+cp -R /tmp/jekyll/* ./
+git add -A .
+git commit -m "Site published on $(date)"
+git push origin master
+git checkout source
+git clean -f -d
+rm -rf /tmp/jekyll
+echo "Site published successfully."
